import { db, schema } from "@/lib/db";
import { eq } from "drizzle-orm";
import { BottomNav } from "@/components/BottomNav";
import { TopBar } from "@/components/TopBar";
import { AreaChip } from "@/components/AreaChip";
import { AREAS, isAreaSlug } from "@/lib/areas";
import { notFound } from "next/navigation";
import { BookmarkButton } from "./BookmarkButton";

export const dynamic = "force-dynamic";

function fmtDate(d: Date): string {
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(d);
}

export default async function ItemPage({ params }: { params: { id: string } }) {
  const id = Number(params.id);
  if (!Number.isFinite(id)) notFound();
  const rows = await db.select().from(schema.developments).where(eq(schema.developments.id, id)).limit(1);
  const item = rows[0];
  if (!item) notFound();
  const areaLabel = isAreaSlug(item.area) ? AREAS[item.area].label : item.area;

  return (
    <main className="min-h-screen bottom-nav-pad top-bar-pad">
      <TopBar title={areaLabel} />
      <article className="px-4 py-5 max-w-prose">
        <div className="flex items-center gap-2 font-sans text-xs text-slate-600">
          {isAreaSlug(item.area) && <AreaChip area={item.area} />}
          <span>{item.firmName}</span>
          <span>·</span>
          <span>{fmtDate(new Date(item.publishedAt))}</span>
        </div>
        <h1 className="mt-2 font-serif text-2xl leading-tight text-ink">{item.title}</h1>
        <div className="mt-4 text-[15px] leading-7 text-slate-800 whitespace-pre-wrap">{item.summary}</div>
        <div className="mt-6 flex flex-col gap-3">
          <a
            href={item.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="block w-full text-center bg-accent text-white rounded-md py-3 font-sans text-sm"
          >
            Open original on {item.firmName} →
          </a>
          <BookmarkButton id={item.id} initial={item.bookmarked} />
        </div>
        <p className="mt-6 text-xs text-slate-500 font-sans">
          Summary generated by an AI model. Always verify against the original source before relying on it.
        </p>
      </article>
      <BottomNav />
    </main>
  );
}
